/*
 * This file is part of the MicroPython project, http://micropython.org/
 *
 * The MIT License (MIT)
 *
 * Copyright (c) 2020-2021 Damien P. George
 * Copyright (c) 2021 Robert Hammelrath
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#include <string.h>

#include "py/runtime.h"
#include "py/mphal.h"
#include "py/mperrno.h"
#include "extmod/modmachine.h"
#include CLOCK_CONFIG_H

#include "fsl_cache.h"
#include "fsl_dmamux.h"
#include "fsl_iomuxc.h"
#include "fsl_lpspi.h"
#include "fsl_lpspi_edma.h"
#include "fsl_pit.h"
#include "fsl_xbara.h"
#include "dma_manager.h"

// --- Periodic DMA transfer extension (SPI.dma_periodic_start() and friends) ---
//
// Added to drive a fixed-rate register update (e.g. a DDS phase/frequency tuning word)
// with hardware timing, independent of CPU polling -- ordinary machine.SPI.write() here
// calls LPSPI_MasterTransferBlocking() (see machine_spi_transfer() below), a fully
// synchronous, CPU-blocking call with no DMA involvement at all; measured sustained
// throughput for that path was ~2000Hz when interleaved with real-time audio I2S, far
// short of a 192kHz per-sample DDS update target. See this project's own memory/design
// notes (not reproduced here) for the fuller rationale; this comment covers only the
// verified hardware facts this implementation depends on.
//
// Verified against the actual vendored SDK/device headers for this chip (i.MX RT1062),
// not assumed:
//   - PIT and GPT have NO entry in the dma_request_source_t enum
//     (sdk/devices/MIMXRT1062/MIMXRT1062.h) -- neither can trigger DMAMUX directly.
//   - An EARLIER version of this file used Quad Timer (QTMR2)'s "Comparator Preload"
//     DMA request for the trigger. Bench-tested 2026-09-06 and found NOT to work: that
//     mechanism is tied to the CMPLD1->COMP1 double-buffered reload feature (a
//     producer/consumer relationship for auto-refreshing a compare value via DMA), not a
//     bare "period elapsed" pulse -- confirmed via a dedicated ISR-count diagnostic
//     (spi_dma_isr_count(), kept in this file -- see dma_periodic_isr_count() below)
//     showing zero interrupts over a 30s run despite the DDS output looking stable (that
//     stability was just the initial blocking-write priming value, latched and held by
//     the chip, never actually refreshed by DMA). Use the same counter to confirm PIT's
//     interrupt actually reaches this callback before trusting this replacement either.
//   - Replaced with PIT + XBARA1. PIT_StartTimer()'s own doc comment
//     (sdk/drivers/pit/fsl_pit.h) says a channel "generates a trigger pulse" every time
//     it reaches 0, unconditionally -- no compare/capture/reload complexity, this is
//     PIT's entire purpose. That trigger has no direct DMAMUX entry, but XBARA1 has a
//     dedicated input for it (kXBARA1_InputPitTrigger0, MIMXRT1062.h) routable to one of
//     XBARA1's 4 DMAMUX-facing outputs (kXBARA1_OutputDmaChMuxReq30, confirmed to be the
//     same physical signal as DMAMUX's own kDmaRequestMuxXBAR1Request0 by cross-
//     referencing the request number in both enums' comments).
//   - I/O_UPDATE (2026-09-06, REVISED -- see below): originally generated by TMR3
//     channel 3's hardware PWM on pin D15 (native alt-function mux
//     IOMUXC_GPIO_AD_B1_03_QTIMER3_TIMER3). Bench-tested with a digital logic capture
//     (ADALM2000, SCK/UPD/MOSI/CS) and found to genuinely DRIFT relative to the
//     PIT-sourced SPI trigger: every I/O_UPDATE rising edge landed at a different,
//     cyclically-repeating percentage through the CS-low window (28%, 78%, 97%, 14%, ...)
//     -- a real beat frequency, not a fixed offset needing one calibration. Root cause:
//     PIT is clocked from PERCLK (CLOCK_GetPerClkFreq()) while QTMR is clocked from
//     IPG_CLK (CLOCK_GetFreq(kCLOCK_IpgClk)) -- two independent, non-phase-locked clock
//     roots, so no amount of one-time phase tuning holds over time.
//   - FIXED by deriving I/O_UPDATE from PIT's OWN clock domain instead: two more PIT
//     channels (SPI_DMA_IO_UPDATE_RISE_PIT_CHANNEL, SPI_DMA_IO_UPDATE_FALL_PIT_CHANNEL),
//     same PERCLK root as the SPI trigger channel, each routed through its own XBARA1
//     input/output pair into its own small self-linked eDMA channel that writes a single
//     constant 32-bit bitmask directly to GPIO1's write-only DR_SET (rising edge) or
//     DR_CLEAR (falling edge) register for pin D15 (SoC pad GPIO_AD_B1_03 = GPIO1 bit 19,
//     confirmed via IOMUXC_GPIO_AD_B1_03_GPIO1_IO19 and the GPIO_Type layout in
//     MIMXRT1062.h -- DR_SET/DR_CLEAR/DR_TOGGLE are the atomic, write-only,
//     read-modify-write-free bitmask registers this chip provides specifically so
//     software/DMA can set/clear individual pins without touching others). D15 is
//     therefore now plain GPIO output (IOMUXC_GPIO_AD_B1_03_GPIO1_IO19), not
//     QTIMER3_TIMER3 -- TMR3 is no longer used anywhere in this file.
//   - The fixed phase offset between PIT channel 0 (SPI trigger) and channels 1/2
//     (I/O_UPDATE rise/fall) is created with a one-time trick, not a running
//     calibration: PIT_SetTimerPeriod() writes LDVAL, and per fsl_pit.h's own
//     PIT_StartTimer()/PIT_SetTimerPeriod() doc comments, a channel only reloads CVAL
//     from LDVAL when it reaches 0 -- writing a new LDVAL while a channel is already
//     counting does not disturb the in-flight countdown. So each offset channel is
//     started with a short, one-shot LDVAL equal to its desired offset (in PIT ticks
//     from a shared t=0), then its LDVAL is immediately rewritten to the full period --
//     that only takes effect on the SECOND and subsequent reloads, leaving the channel
//     forever after firing at (offset, offset+period, offset+2*period, ...) relative to
//     channel 0's own (period, 2*period, ...), with zero drift since all three channels
//     share the identical PERCLK root by construction. The only skew is the handful of
//     CPU cycles between the three PIT_StartTimer() calls in dma_periodic_start() below
//     -- fixed at start time, not accumulating, and far smaller than one PERCLK tick's
//     worth of the datasheet's I/O_UPDATE setup/hold budget.
//   - LPSPI's own automatic FIFO-empty DMA request (its DER register) is deliberately
//     NOT used or enabled anywhere in this file -- it would be paced by the SPI baud
//     rate, not by the PIT-sourced 192kHz trigger, and the two must not both drive the
//     same DMAMUX channel. Writes to TDR here happen unconditionally at the PIT's pace;
//     the caller is responsible for choosing a baudrate high enough that one frame's
//     clock-out time stays comfortably under one rate_hz period (e.g. an 8-byte AD9910
//     Profile 0 write is 64 bits; at 192kHz that leaves ~5.2us, so a >=20Mbps baudrate
//     is needed for real margin -- NOT YET BENCH-VALIDATED, see the module's own
//     dma_periodic_start() docstring below).
//
// NOT yet verified -- real open items, deliberately left as runtime-computed or
// explicit caller-supplied values rather than guessed constants:
//   - The exact PIT channel-0 tick count for a given rate_hz: computed at
//     spi_dma_periodic_start() time from CLOCK_GetPerClkFreq(), the accessor this SDK
//     provides specifically for PIT's own clock root, not hardcoded. NOT yet bench-
//     confirmed that PIT's trigger actually reaches the eDMA channel end to end (that's
//     the immediate next thing to verify, after QTMR2's mechanism turned out not to).
//   - I/O_UPDATE pulse width/phase relative to the SPI frame's completion -- exposed as
//     explicit io_update_duty_u16/io_update_phase_ticks arguments rather than a default,
//     because getting this wrong either misses the datasheet's I/O_UPDATE setup/hold
//     window or clips into the next frame; needs ADALM2000 bench measurement. The DRIFT
//     problem itself is now architecturally fixed (both channels share PIT's clock --
//     see the revised bullet above), but the specific NUMBER of ticks that lands safely
//     after a frame completes is still a bench-measured quantity, not derived here.
//   - Whether PIT channels 0-2, XBARA1 outputs 0-2, and two extra eDMA channels are free
//     at runtime on top of whatever else the running firmware claims (this file does not
//     check for conflicts with other code that might already be using them -- a real
//     gap, not yet handled).
//   - D-cache coherency around the ring buffer (RESOLVED 2026-09-06): a frequency-sweep
//     bench test found this exact gap for real -- dma_periodic_write() calls succeeded
//     and produced genuinely varying content (confirmed via the Teensy's own debug log),
//     but the DDS output never changed, stuck on whatever the first write left in RAM.
//     Fixed by adding DCACHE_CleanByRange() after both the initial memset() in
//     dma_periodic_start() and every memcpy() in dma_periodic_write(). Re-verify the
//     sweep test again with this fix before considering it fully closed.
//   - Multi-byte frame bit-ordering on the wire, end to end. dma_periodic_start() widens
//     LPSPI's TCR.FRAMESZ so hardware holds chip-select low across a whole
//     instruction-byte+payload frame instead of toggling it every byte (see that
//     function's own comment for why this is a read-modify-write with a real
//     precondition, not a from-scratch TCR reconstruction) -- but nobody has yet
//     compared a byte captured off this DMA path against a known-good blocking-mode
//     write of the same register on a logic analyzer. Do not trust this produces a
//     correct AD9910/9952/9954 register write until that comparison has been done.

#define DEFAULT_SPI_ID          (0)
#define DEFAULT_SPI_BAUDRATE    (1000000)
#define DEFAULT_SPI_POLARITY    (0)
#define DEFAULT_SPI_PHASE       (0)
#define DEFAULT_SPI_BITS        (8)
#define DEFAULT_SPI_FIRSTBIT    (kLPSPI_MsbFirst)
#define DEFAULT_SPI_DRIVE       (6)

#define CLOCK_DIVIDER           (1)

#if defined(MIMXRT117x_SERIES)
#define LPSPI_DMAMUX            DMAMUX0
#else
#define LPSPI_DMAMUX            DMAMUX
#endif

#define MICROPY_HW_SPI_NUM MP_ARRAY_SIZE(spi_index_table)

#define SCK (iomux_table[index])
#define CS0 (iomux_table[index + 1])
#define SDO (iomux_table[index + 2])
#define SDI (iomux_table[index + 3])
#define CS1 (iomux_table[index + 4])

// PIT channel 0 is dedicated as the periodic-DMA trigger for ALL SPI(id) objects that
// use dma_periodic_start() -- this project only ever needs one such stream at a time
// (the DDS phase path), so no per-instance allocation is implemented. PIT channels 1 and
// 2 are dedicated as the I/O_UPDATE rise/fall generators (see the module-level comment
// above for why this replaced TMR3's PWM -- clock-domain drift between PIT/PERCLK and
// QTMR/IPG_CLK, confirmed on the bench).
// Trigger mechanism (2026-09-06, revised): NOT QTMR2 anymore -- bench-tested and found
// that QTMR's "Comparator Preload" DMA request is tied to the CMPLD1->COMP1 double-
// buffered reload mechanism (a producer/consumer relationship for auto-updating a
// compare value via DMA), not a bare "period elapsed" pulse; nothing ever primed
// CMPLD1, so the request never fired (confirmed via a dedicated ISR-count diagnostic:
// zero interrupts over a 30s run despite the DDS output looking stable -- that stability
// was just the initial blocking-write priming value, latched and held, never actually
// refreshed by DMA).
//
// Replaced with PIT + XBARA1, verified against the device header (not assumed):
// PIT_StartTimer()'s own doc says a channel "generates a trigger pulse" unconditionally
// every time it reaches 0 -- no compare/capture/reload complexity attached, this is
// PIT's entire purpose. That trigger has no direct DMAMUX entry (confirmed earlier --
// PIT and GPT are both absent from dma_request_source_t), but XBARA1 has a dedicated
// input for it (kXBARA1_InputPitTrigger0, MIMXRT1062.h) which can be routed to one of
// XBARA1's 4 DMAMUX-facing outputs (kXBARA1_OutputDmaChMuxReq30, matching DMAMUX's own
// kDmaRequestMuxXBAR1Request0 -- confirmed these are the same physical signal by cross-
// referencing the request-number in both enums' comments). PIT channel 0, XBARA1 output
// 0 chosen; nothing else in this codebase uses either.
#define SPI_DMA_PIT_CHANNEL         kPIT_Chnl_0
#define SPI_DMA_XBAR_INPUT          kXBARA1_InputPitTrigger0
#define SPI_DMA_XBAR_OUTPUT         kXBARA1_OutputDmaChMuxReq30
#define SPI_DMA_DMAMUX_SRC          kDmaRequestMuxXBAR1Request0

// I/O_UPDATE rise/fall: two more PIT channels, same PERCLK root as SPI_DMA_PIT_CHANNEL
// above, each routed through its own XBARA1 input/output pair to its own small eDMA
// channel that toggles pin D15 (GPIO1 bit 19) directly via GPIO1's DR_SET/DR_CLEAR
// registers. See the module-level comment for why this replaced TMR3's PWM and how the
// fixed phase offset between these and SPI_DMA_PIT_CHANNEL is created.
#define SPI_DMA_IO_UPDATE_RISE_PIT_CHANNEL   kPIT_Chnl_1
#define SPI_DMA_IO_UPDATE_RISE_XBAR_INPUT    kXBARA1_InputPitTrigger1
#define SPI_DMA_IO_UPDATE_RISE_XBAR_OUTPUT   kXBARA1_OutputDmaChMuxReq31
#define SPI_DMA_IO_UPDATE_RISE_DMAMUX_SRC    kDmaRequestMuxXBAR1Request1
#define SPI_DMA_IO_UPDATE_FALL_PIT_CHANNEL   kPIT_Chnl_2
#define SPI_DMA_IO_UPDATE_FALL_XBAR_INPUT    kXBARA1_InputPitTrigger2
#define SPI_DMA_IO_UPDATE_FALL_XBAR_OUTPUT   kXBARA1_OutputDmaChMuxReq94
#define SPI_DMA_IO_UPDATE_FALL_DMAMUX_SRC    kDmaRequestMuxXBAR1Request2

// D15 = SoC pad GPIO_AD_B1_03 = GPIO1 bit 19 in plain-GPIO alt-function mode (confirmed
// via IOMUXC_GPIO_AD_B1_03_GPIO1_IO19, sdk/devices/MIMXRT1062/drivers/fsl_iomuxc.h).
#define SPI_DMA_IO_UPDATE_GPIO_BASE  GPIO1
#define SPI_DMA_IO_UPDATE_GPIO_BIT   (19u)

// Ring buffer size: two equal halves, refilled one half at a time while the DMA engine
// drains the other -- same double-buffering shape as machine_i2s.c's SIZEOF_DMA_BUFFER_
// IN_BYTES/feed_dma() pattern, sized in frames rather than assumed a fixed byte count
// since frame_bytes is caller-specified (5 bytes for an AD9952/9954-style FTW0 write, 8
// for an AD9910 Profile 0 write, etc.).
#define SPI_DMA_FRAMES_PER_HALF (64)

typedef struct _machine_spi_obj_t {
    mp_obj_base_t base;
    uint8_t spi_id;
    uint8_t mode;
    uint8_t spi_hw_id;
    bool transfer_busy;
    LPSPI_Type *spi_inst;
    lpspi_master_config_t *master_config;

    // --- periodic DMA extension state; all zero/NULL unless dma_periodic_start() has
    // been called on this object. See the module-level comment block above.
    bool dma_periodic_active;
    size_t dma_frame_bytes;
    uint8_t *dma_buffer;                 // 2 * SPI_DMA_FRAMES_PER_HALF * dma_frame_bytes,
                                          // allocated at dma_periodic_start() time
    uint8_t *dma_buffer_dcache_aligned;
    int dma_channel;
    edma_handle_t dma_edmaHandle;
    edma_tcd_t *dma_edmaTcd;
    mp_obj_t dma_refill_callback;         // called via mp_sched_schedule(cb, half_index)

    // --- I/O_UPDATE rise/fall eDMA channels (GPIO1 DR_SET/DR_CLEAR toggle via PIT
    // channels 1/2 + XBARA1, not TMR3 -- see the module-level comment block). Only
    // valid while dma_periodic_active is true, same as the fields above.
    int dma_io_update_set_channel;
    int dma_io_update_clear_channel;
    edma_handle_t dma_io_update_set_edmaHandle;
    edma_handle_t dma_io_update_clear_edmaHandle;
} machine_spi_obj_t;

typedef struct _iomux_table_t {
    uint32_t muxRegister;
    uint32_t muxMode;
    uint32_t inputRegister;
    uint32_t inputDaisy;
    uint32_t configRegister;
} iomux_table_t;

static const uint8_t spi_index_table[] = MICROPY_HW_SPI_INDEX;
static LPSPI_Type *spi_base_ptr_table[] = LPSPI_BASE_PTRS;
static const iomux_table_t iomux_table[] = {
    IOMUX_TABLE_SPI
};

bool lpspi_set_iomux(int8_t spi, uint8_t drive, int8_t cs) {
    int index = (spi - 1) * 5;

    if (SCK.muxRegister != 0) {
        IOMUXC_SetPinMux(SCK.muxRegister, SCK.muxMode, SCK.inputRegister, SCK.inputDaisy, SCK.configRegister, 0U);
        IOMUXC_SetPinConfig(SCK.muxRegister, SCK.muxMode, SCK.inputRegister, SCK.inputDaisy, SCK.configRegister,
            pin_generate_config(PIN_PULL_UP_100K, PIN_MODE_OUT, drive, SCK.configRegister));

        if (cs == 0 && CS0.muxRegister != 0) {
            IOMUXC_SetPinMux(CS0.muxRegister, CS0.muxMode, CS0.inputRegister, CS0.inputDaisy, CS0.configRegister, 0U);
            IOMUXC_SetPinConfig(CS0.muxRegister, CS0.muxMode, CS0.inputRegister, CS0.inputDaisy, CS0.configRegister,
                pin_generate_config(PIN_PULL_UP_100K, PIN_MODE_OUT, drive, CS0.configRegister));
        } else if (cs == 1 && CS1.muxRegister != 0) {
            IOMUXC_SetPinMux(CS1.muxRegister, CS1.muxMode, CS1.inputRegister, CS1.inputDaisy, CS1.configRegister, 0U);
            IOMUXC_SetPinConfig(CS1.muxRegister, CS1.muxMode, CS1.inputRegister, CS1.inputDaisy, CS1.configRegister,
                pin_generate_config(PIN_PULL_UP_100K, PIN_MODE_OUT, drive, CS1.configRegister));
        } else if (cs != -1) {
            mp_raise_ValueError(MP_ERROR_TEXT("The chosen CS is not available"));
        }

        IOMUXC_SetPinMux(SDO.muxRegister, SDO.muxMode, SDO.inputRegister, SDO.inputDaisy, SDO.configRegister, 0U);
        IOMUXC_SetPinConfig(SDO.muxRegister, SDO.muxMode, SDO.inputRegister, SDO.inputDaisy, SDO.configRegister,
            pin_generate_config(PIN_PULL_UP_100K, PIN_MODE_OUT, drive, SDO.configRegister));

        IOMUXC_SetPinMux(SDI.muxRegister, SDI.muxMode, SDI.inputRegister, SDI.inputDaisy, SDI.configRegister, 0U);
        IOMUXC_SetPinConfig(SDI.muxRegister, SDI.muxMode, SDI.inputRegister, SDI.inputDaisy, SDI.configRegister,
            pin_generate_config(PIN_PULL_UP_100K, PIN_MODE_IN, drive, SDI.configRegister));

        return true;
    } else {
        return false;
    }
}

static void machine_spi_print(const mp_print_t *print, mp_obj_t self_in, mp_print_kind_t kind) {
    static const char *firstbit_str[] = {"MSB", "LSB"};
    machine_spi_obj_t *self = MP_OBJ_TO_PTR(self_in);
    mp_printf(print, "SPI(%u, baudrate=%u, polarity=%u, phase=%u, bits=%u, firstbit=%s, gap_ns=%d)",
        self->spi_id, self->master_config->baudRate, self->master_config->cpol,
        self->master_config->cpha, self->master_config->bitsPerFrame,
        firstbit_str[self->master_config->direction], self->master_config->betweenTransferDelayInNanoSec);
}

mp_obj_t machine_spi_make_new(const mp_obj_type_t *type, size_t n_args, size_t n_kw, const mp_obj_t *all_args) {
    enum { ARG_id, ARG_baudrate, ARG_polarity, ARG_phase, ARG_bits, ARG_firstbit, ARG_gap_ns, ARG_drive, ARG_cs };
    static const mp_arg_t allowed_args[] = {
        { MP_QSTR_id,       MP_ARG_INT, {.u_int = DEFAULT_SPI_ID} },
        { MP_QSTR_baudrate, MP_ARG_INT, {.u_int = DEFAULT_SPI_BAUDRATE} },
        { MP_QSTR_polarity, MP_ARG_KW_ONLY | MP_ARG_INT, {.u_int = DEFAULT_SPI_POLARITY} },
        { MP_QSTR_phase,    MP_ARG_KW_ONLY | MP_ARG_INT, {.u_int = DEFAULT_SPI_PHASE} },
        { MP_QSTR_bits,     MP_ARG_KW_ONLY | MP_ARG_INT, {.u_int = DEFAULT_SPI_BITS} },
        { MP_QSTR_firstbit, MP_ARG_KW_ONLY | MP_ARG_INT, {.u_int = DEFAULT_SPI_FIRSTBIT} },
        { MP_QSTR_gap_ns,   MP_ARG_KW_ONLY | MP_ARG_INT, {.u_int = -1} },
        { MP_QSTR_drive,    MP_ARG_KW_ONLY | MP_ARG_INT, {.u_int = DEFAULT_SPI_DRIVE} },
        { MP_QSTR_cs,       MP_ARG_KW_ONLY | MP_ARG_INT, {.u_int = -1} },
    };

    // Parse the arguments.
    mp_arg_val_t args[MP_ARRAY_SIZE(allowed_args)];
    mp_arg_parse_all_kw_array(n_args, n_kw, all_args, MP_ARRAY_SIZE(allowed_args), allowed_args, args);

    // Get the SPI bus id.
    int spi_id = args[ARG_id].u_int;
    if (spi_id < 0 || spi_id >= MP_ARRAY_SIZE(spi_index_table) || spi_index_table[spi_id] == 0) {
        mp_raise_msg_varg(&mp_type_ValueError, MP_ERROR_TEXT("SPI(%d) doesn't exist"), spi_id);
    }

    // Get peripheral object.
    uint8_t spi_hw_id = spi_index_table[spi_id];  // the hw spi number 1..n
    machine_spi_obj_t *self = mp_obj_malloc(machine_spi_obj_t, &machine_spi_type);
    self->spi_id = spi_id;
    self->spi_inst = spi_base_ptr_table[spi_hw_id];
    self->spi_hw_id = spi_hw_id;
    self->dma_periodic_active = false;
    self->dma_buffer = NULL;
    self->dma_refill_callback = MP_OBJ_NULL;
    self->dma_io_update_set_channel = -1;
    self->dma_io_update_clear_channel = -1;

    uint8_t drive = args[ARG_drive].u_int;
    if (drive < 1 || drive > 7) {
        drive = DEFAULT_SPI_DRIVE;
    }

    LPSPI_Reset(self->spi_inst);
    LPSPI_Enable(self->spi_inst, false);  // Disable first before new settings are applies

    self->master_config = m_new_obj(lpspi_master_config_t);
    LPSPI_MasterGetDefaultConfig(self->master_config);
    // Initialise the SPI peripheral.
    self->master_config->baudRate = args[ARG_baudrate].u_int;
    self->master_config->betweenTransferDelayInNanoSec = 1000000000 / self->master_config->baudRate * 2;
    self->master_config->cpol = args[ARG_polarity].u_int;
    self->master_config->cpha = args[ARG_phase].u_int;
    self->master_config->bitsPerFrame = args[ARG_bits].u_int;
    self->master_config->direction = args[ARG_firstbit].u_int;
    if (args[ARG_gap_ns].u_int != -1) {
        self->master_config->betweenTransferDelayInNanoSec = args[ARG_gap_ns].u_int;
    }
    self->master_config->lastSckToPcsDelayInNanoSec = self->master_config->betweenTransferDelayInNanoSec;
    self->master_config->pcsToSckDelayInNanoSec = self->master_config->betweenTransferDelayInNanoSec;
    int8_t cs = args[ARG_cs].u_int;
    // In the SPI master_config for automatic CS the value cs=0 is set already,
    // so only cs=1 has to be addressed here. The case cs == -1 for manual CS is handled
    // in the function spi_set_iomux() and the value in the master_config can stay at 0.
    if (cs == 1) {
        self->master_config->whichPcs = cs;
    }
    LPSPI_MasterInit(self->spi_inst, self->master_config, BOARD_BOOTCLOCKRUN_LPSPI_CLK_ROOT);
    lpspi_set_iomux(spi_index_table[spi_id], drive, cs);

    return MP_OBJ_FROM_PTR(self);
}

static void machine_spi_init(mp_obj_base_t *self_in, size_t n_args, const mp_obj_t *pos_args, mp_map_t *kw_args) {
    enum { ARG_baudrate, ARG_polarity, ARG_phase, ARG_bits, ARG_firstbit, ARG_gap_ns };
    static const mp_arg_t allowed_args[] = {
        { MP_QSTR_baudrate, MP_ARG_KW_ONLY | MP_ARG_INT, {.u_int = -1} },
        { MP_QSTR_polarity, MP_ARG_KW_ONLY | MP_ARG_INT, {.u_int = -1} },
        { MP_QSTR_phase,    MP_ARG_KW_ONLY | MP_ARG_INT, {.u_int = -1} },
        { MP_QSTR_bits,     MP_ARG_KW_ONLY | MP_ARG_INT, {.u_int = -1} },
        { MP_QSTR_firstbit, MP_ARG_KW_ONLY | MP_ARG_INT, {.u_int = -1} },
        { MP_QSTR_gap_ns,   MP_ARG_KW_ONLY | MP_ARG_INT, {.u_int = -1} },
    };

    // Parse the arguments.
    machine_spi_obj_t *self = (machine_spi_obj_t *)self_in;
    mp_arg_val_t args[MP_ARRAY_SIZE(allowed_args)];
    mp_arg_parse_all(n_args, pos_args, kw_args, MP_ARRAY_SIZE(allowed_args), allowed_args, args);

    // Reconfigure the baudrate if requested.
    if (args[ARG_baudrate].u_int != -1) {
        self->master_config->baudRate = args[ARG_baudrate].u_int;
        self->master_config->betweenTransferDelayInNanoSec = 1000000000 / self->master_config->baudRate * 2;
    }
    // Reconfigure the format if requested.
    if (args[ARG_polarity].u_int != -1) {
        self->master_config->cpol = args[ARG_polarity].u_int;
    }
    if (args[ARG_phase].u_int != -1) {
        self->master_config->cpha = args[ARG_phase].u_int;
    }
    if (args[ARG_bits].u_int != -1) {
        self->master_config->bitsPerFrame = args[ARG_bits].u_int;
    }
    if (args[ARG_firstbit].u_int != -1) {
        self->master_config->direction = args[ARG_firstbit].u_int;
    }
    if (args[ARG_gap_ns].u_int != -1) {
        self->master_config->betweenTransferDelayInNanoSec = args[ARG_gap_ns].u_int;
    }
    self->master_config->lastSckToPcsDelayInNanoSec = self->master_config->betweenTransferDelayInNanoSec;
    self->master_config->pcsToSckDelayInNanoSec = self->master_config->betweenTransferDelayInNanoSec;
    LPSPI_Enable(self->spi_inst, false);  // Disable first before new settings are applies
    LPSPI_MasterInit(self->spi_inst, self->master_config, BOARD_BOOTCLOCKRUN_LPSPI_CLK_ROOT);
}

static void machine_spi_transfer(mp_obj_base_t *self_in, size_t len, const uint8_t *src, uint8_t *dest) {
    machine_spi_obj_t *self = (machine_spi_obj_t *)self_in;

    if (len > 0) {
        // Wait a short while for the previous transfer to finish, but not forever
        for (volatile int j = 0; (j < 5000) && ((self->spi_inst->SR & kLPSPI_ModuleBusyFlag) != 0); j++) {}

        lpspi_transfer_t masterXfer;
        masterXfer.txData = (uint8_t *)src;
        masterXfer.rxData = (uint8_t *)dest;
        masterXfer.dataSize = len;
        masterXfer.configFlags = (self->master_config->whichPcs << LPSPI_MASTER_PCS_SHIFT) | kLPSPI_MasterPcsContinuous | kLPSPI_MasterByteSwap;

        if (LPSPI_MasterTransferBlocking(self->spi_inst, &masterXfer) != kStatus_Success) {
            mp_raise_OSError(EIO);
        }
    }
}

// Forward declaration -- defined further down with the rest of the periodic-DMA
// implementation, but must be wired into machine_spi_p (right below) so a plain
// spi.deinit() (or garbage collection reclaiming an abandoned SPI object -- a real
// scenario given this project's habit of re-running bench scripts repeatedly in the
// same mpremote/REPL session) actually releases all the DMA channels and stops all the
// PIT channels this extension uses, instead of leaking them silently. Before this,
// machine_spi_p had no .deinit at all (generic machine_spi_deinit() in extmod/
// machine_spi.c already no-ops when it's NULL) -- a pre-existing gap this patch also
// closes as a side effect.
static void machine_spi_deinit_hw(mp_obj_base_t *self_in);

static const mp_machine_spi_p_t machine_spi_p = {
    .init = machine_spi_init,
    .deinit = machine_spi_deinit_hw,
    .transfer = machine_spi_transfer,
};

// --- Periodic DMA transfer implementation ---
// See the module-level comment block near the top of this file for the verified
// hardware facts this depends on, and what's still open.

// TCD storage for the periodic-DMA channel. Only one SPI(id) can run dma_periodic_start()
// at a time in this implementation (see SPI_DMA_PIT_CHANNEL's own comment), so a single
// static TCD suffices -- mirrors machine_i2s.c's AT_NONCACHEABLE_SECTION_ALIGN(edma_tcd_t
// edmaTcd[I2S_NUM_OBJ_SLOTS], 32) pattern, sized 1 instead of I2S_NUM_OBJ_SLOTS.
AT_NONCACHEABLE_SECTION_ALIGN(static edma_tcd_t spi_dma_tcd, 32);

// TCD storage + constant source words for the two I/O_UPDATE toggle channels (GPIO1
// DR_SET/DR_CLEAR writes). Each is a single fixed 4-byte transfer per PIT trigger, self-
// linked like spi_dma_tcd above -- no ring buffer needed since the content never
// changes, only the destination register (SET vs CLEAR) differs between the two. Living
// in a non-cacheable section (like spi_dma_tcd) means no DCACHE_CleanByRange() call is
// needed even though dma_periodic_start() writes the mask value at runtime.
AT_NONCACHEABLE_SECTION_ALIGN(static edma_tcd_t spi_dma_io_update_set_tcd, 32);
AT_NONCACHEABLE_SECTION_ALIGN(static edma_tcd_t spi_dma_io_update_clear_tcd, 32);
AT_NONCACHEABLE_SECTION_ALIGN(static uint32_t spi_dma_io_update_gpio_bit_mask, 4);

// Diagnostic-only counter (2026-09-06): increments unconditionally, at ISR level, every
// time this callback runs at all -- independent of whether mp_sched_schedule() actually
// gets serviced by the Python side. Used to separate "the eDMA interrupt never fires" from
// "it fires but the scheduled Python callback never runs" after a sweep test found
// refill() only ever called twice (the initial manual primes) in a 30s run.
volatile uint32_t spi_dma_isr_count = 0;

static void edma_spi_periodic_callback(edma_handle_t *handle, void *userData, bool transferDone, uint32_t tcds) {
    spi_dma_isr_count++;
    machine_spi_obj_t *self = (machine_spi_obj_t *)userData;
    if (self->dma_refill_callback != MP_OBJ_NULL && self->dma_refill_callback != mp_const_none) {
        // transferDone == true means the eDMA major loop just wrapped, i.e. the bottom
        // half was the one just drained (mirrors edma_i2s_callback's own TOP_HALF/
        // BOTTOM_HALF convention in machine_i2s.c) -- pass which half needs refilling,
        // not which half just played, so the Python-side callback can call
        // dma_periodic_write() directly on the right half without re-deriving this.
        mp_sched_schedule(self->dma_refill_callback,
            MP_OBJ_NEW_SMALL_INT(transferDone ? 0 : 1));
    }
}

// spi.dma_periodic_start(frame_bytes, rate_hz, refill_callback, io_update_duty_u16=0,
//                         io_update_phase_ticks=0)
//
// Starts a PIT/eDMA-driven periodic transfer of `frame_bytes`-sized frames from an
// internal double-buffer into this SPI object's LPSPI TDR register at `rate_hz`, and an
// I/O_UPDATE pulse on pin D15 at the same rate -- generated by two MORE PIT channels
// (sharing the same PERCLK root as the SPI-triggering channel, see the module comment)
// driving GPIO1 directly via eDMA, not TMR3's PWM.
// `refill_callback(half)` is scheduled (via mp_sched_schedule, i.e. run on the main
// thread, not from IRQ context) each time a half-buffer has just been drained and needs
// fresh frames written into it via dma_periodic_write(half, buf).
//
// `io_update_duty_u16` is the I/O_UPDATE pulse width as a fraction of the full period
// (0..65535 maps to 0..rate_hz's period); 0 means "no I/O_UPDATE pulse is generated,"
// i.e. this call alone is NOT sufficient for a working DDS update path. `io_update_
// phase_ticks` is the rising-edge delay in PIT ticks from the same start reference the
// SPI-triggering channel counts from; 0 picks a default (80% of the period) rather than
// a caller-required value, but that default is NOT bench-derived -- see the module
// comment's open-items list. The clock-DOMAIN drift problem this design replaces (PIT
// vs. TMR3/QTMR, confirmed on the bench 2026-09-06) is fixed by construction now: only
// the exact tick counts remain a bench-tuning question, not whether the two stay locked.
static mp_obj_t machine_spi_dma_periodic_start(size_t n_args, const mp_obj_t *args) {
    machine_spi_obj_t *self = MP_OBJ_TO_PTR(args[0]);
    mp_int_t frame_bytes = mp_obj_get_int(args[1]);
    mp_int_t rate_hz = mp_obj_get_int(args[2]);
    mp_obj_t refill_callback = args[3];
    mp_int_t io_update_duty_u16 = (n_args > 4) ? mp_obj_get_int(args[4]) : 0;
    mp_int_t io_update_phase_ticks = (n_args > 5) ? mp_obj_get_int(args[5]) : 0;

    if (self->dma_periodic_active) {
        mp_raise_msg(&mp_type_OSError, MP_ERROR_TEXT("dma_periodic already active"));
    }
    if (frame_bytes <= 0 || frame_bytes > 16) {
        mp_raise_ValueError(MP_ERROR_TEXT("frame_bytes out of range"));
    }

    self->dma_frame_bytes = (size_t)frame_bytes;
    size_t half_bytes = SPI_DMA_FRAMES_PER_HALF * self->dma_frame_bytes;
    size_t total_bytes = 2 * half_bytes;

    // +0x1f for D-cache-line alignment slack, same as machine_i2s.c's dma_buffer field;
    // AT_NONCACHEABLE_SECTION_ALIGN is not used here because size is only known at this
    // point (frame_bytes is caller-specified), unlike the fixed-size TCD above -- this
    // buffer instead needs an explicit cache-maintenance call before each DMA-visible
    // write -- confirmed necessary by bench test (2026-09-06): a frequency-sweep test
    // wrote genuinely changing content via dma_periodic_write() on every refill (verified
    // via the Teensy's own debug log), but the DDS output never changed, stuck at
    // whatever the very first write happened to leave in RAM -- exactly the D-cache
    // staleness this TODO predicted (CPU writes land in cache, DMA reads RAM directly,
    // never sees the update without an explicit clean).
    self->dma_buffer = m_new(uint8_t, total_bytes + 0x1f);
    self->dma_buffer_dcache_aligned = (uint8_t *)(((uint32_t)self->dma_buffer + 0x1f) & ~0x1f);
    memset(self->dma_buffer_dcache_aligned, 0, total_bytes);
    DCACHE_CleanByRange((uint32_t)self->dma_buffer_dcache_aligned, (uint32_t)total_bytes);

    self->dma_refill_callback = refill_callback;

    // --- PIT channel 0: unconditional periodic trigger pulse, routed via XBARA1 into
    // DMAMUX. See SPI_DMA_PIT_CHANNEL's own comment above for why this replaced QTMR2.
    pit_config_t pit_config;
    PIT_GetDefaultConfig(&pit_config);
    PIT_Init(PIT, &pit_config);
    uint32_t perclk_hz = CLOCK_GetPerClkFreq();
    uint32_t pit_ticks = perclk_hz / (uint32_t)rate_hz;
    if (pit_ticks == 0) {
        mp_raise_ValueError(MP_ERROR_TEXT("rate_hz too high to represent on PIT"));
    }
    PIT_SetTimerPeriod(PIT, SPI_DMA_PIT_CHANNEL, pit_ticks);

    XBARA_Init(XBARA1);
    XBARA_SetSignalsConnection(XBARA1, SPI_DMA_XBAR_INPUT, SPI_DMA_XBAR_OUTPUT);
    xbara_control_config_t xbar_ctrl_config = {
        .activeEdge = kXBARA_EdgeRising,
        .requestType = kXBARA_RequestDMAEnable,
    };
    XBARA_SetOutputSignalConfig(XBARA1, SPI_DMA_XBAR_OUTPUT, &xbar_ctrl_config);

    // DMAMUX and eDMA (DMA0) must both be initialized before ANY channel is touched --
    // moved up here (both idempotent, DMAMUX_Init() resets/enables the whole module and
    // dma_init() itself is internally guarded against being called twice) because the
    // I/O_UPDATE block below now also allocates/configures two eDMA channels, and this
    // was originally placed further down, after that block -- a real bug found on the
    // bench (2026-09-06 revision 2): with initialization still below, the I/O_UPDATE
    // channels' EDMA_CreateHandle()/DMAMUX_SetSource() calls ran against an
    // uninitialized DMAMUX/DMA0, hanging the board before dma_periodic_start() could
    // ever return.
    dma_init();
    DMAMUX_Init(DMAMUX);

    // --- I/O_UPDATE on pin D15, via PIT channels 1/2 + XBARA1 + two small self-linked
    // eDMA channels toggling GPIO1 directly (DR_SET/DR_CLEAR). See the module-level
    // comment for why this replaced TMR3's PWM (a real, bench-confirmed clock-domain
    // drift between PIT/PERCLK and QTMR/IPG_CLK) and how the fixed phase offset below is
    // created. io_update_duty_u16 == 0 keeps the previous "no I/O_UPDATE pulse
    // generated" behavior -- this call alone still isn't sufficient for a working DDS
    // update path without it.
    if (io_update_duty_u16 > 0) {
        // Both offsets are PIT ticks counted from the same t=0 that SPI_DMA_PIT_CHANNEL
        // itself starts from (its own PIT_StartTimer() call is below, right after these
        // channels' own). Default phase, if the caller passes 0: land the rising edge
        // 80% through the period, leaving margin both for the SPI frame to finish
        // clocking out ahead of it and for the pulse width behind it -- a starting
        // point, NOT a bench-derived value; see the module comment's open-items list.
        uint32_t phase_ticks = (io_update_phase_ticks > 0)
            ? (uint32_t)io_update_phase_ticks
            : (pit_ticks * 4) / 5;
        uint32_t pulse_width_ticks = (uint32_t)(((uint64_t)pit_ticks * (uint32_t)io_update_duty_u16) / 65536);
        if (pulse_width_ticks < 1) {
            pulse_width_ticks = 1;
        }
        if (phase_ticks < 1) {
            phase_ticks = 1;
        }
        if (phase_ticks + pulse_width_ticks >= pit_ticks) {
            if (phase_ticks + 1 >= pit_ticks) {
                mp_raise_ValueError(MP_ERROR_TEXT("io_update_phase_ticks leaves no room in the period"));
            }
            pulse_width_ticks = pit_ticks - phase_ticks - 1;
        }

        // D15 as plain GPIO output (ALT5, GPIO1 bit 19) instead of QTIMER3_TIMER3 -- see
        // the module comment for the pin-mux fact this depends on. Same
        // SetPinMux+SetPinConfig pairing as lpspi_set_iomux() (a real bug -- a missing
        // SetPinConfig call -- was found and fixed on the earlier TMR3-based version of
        // this, and this keeps that fix's pairing rather than repeating the gap).
        IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_03_GPIO1_IO19, 0U);
        IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_03_GPIO1_IO19,
            pin_generate_config(PIN_PULL_UP_100K, PIN_MODE_OUT, DEFAULT_SPI_DRIVE, 0x401F82F8U));
        SPI_DMA_IO_UPDATE_GPIO_BASE->GDIR |= (1u << SPI_DMA_IO_UPDATE_GPIO_BIT);
        SPI_DMA_IO_UPDATE_GPIO_BASE->DR_CLEAR = (1u << SPI_DMA_IO_UPDATE_GPIO_BIT); // start low
        spi_dma_io_update_gpio_bit_mask = (1u << SPI_DMA_IO_UPDATE_GPIO_BIT);

        // --- PIT channels 1 (rise) and 2 (fall): one-shot short LDVAL, started, then
        // immediately rewritten to the full period -- see the module comment for why
        // this creates a fixed, driftless offset instead of a running calibration.
        PIT_SetTimerPeriod(PIT, SPI_DMA_IO_UPDATE_RISE_PIT_CHANNEL, phase_ticks);
        XBARA_SetSignalsConnection(XBARA1, SPI_DMA_IO_UPDATE_RISE_XBAR_INPUT, SPI_DMA_IO_UPDATE_RISE_XBAR_OUTPUT);
        XBARA_SetOutputSignalConfig(XBARA1, SPI_DMA_IO_UPDATE_RISE_XBAR_OUTPUT, &xbar_ctrl_config);

        PIT_SetTimerPeriod(PIT, SPI_DMA_IO_UPDATE_FALL_PIT_CHANNEL, phase_ticks + pulse_width_ticks);
        XBARA_SetSignalsConnection(XBARA1, SPI_DMA_IO_UPDATE_FALL_XBAR_INPUT, SPI_DMA_IO_UPDATE_FALL_XBAR_OUTPUT);
        XBARA_SetOutputSignalConfig(XBARA1, SPI_DMA_IO_UPDATE_FALL_XBAR_OUTPUT, &xbar_ctrl_config);

        // --- Two small eDMA channels: each a single fixed 4-byte write of the same
        // constant bitmask into GPIO1's DR_SET (rise) or DR_CLEAR (fall), self-linked so
        // they keep re-arming forever with no CPU/interrupt involvement -- fire-and-
        // forget, no EDMA_SetCallback, nothing needs to run in software when these fire.
        self->dma_io_update_set_channel = allocate_dma_channel();
        self->dma_io_update_clear_channel = allocate_dma_channel();
        if (self->dma_io_update_set_channel < 0 || self->dma_io_update_clear_channel < 0) {
            mp_raise_msg(&mp_type_OSError, MP_ERROR_TEXT("no DMA channel available for I/O_UPDATE"));
        }
        DMAMUX_SetSource(DMAMUX, self->dma_io_update_set_channel, SPI_DMA_IO_UPDATE_RISE_DMAMUX_SRC);
        DMAMUX_EnableChannel(DMAMUX, self->dma_io_update_set_channel);
        DMAMUX_SetSource(DMAMUX, self->dma_io_update_clear_channel, SPI_DMA_IO_UPDATE_FALL_DMAMUX_SRC);
        DMAMUX_EnableChannel(DMAMUX, self->dma_io_update_clear_channel);

        EDMA_CreateHandle(&self->dma_io_update_set_edmaHandle, DMA0, self->dma_io_update_set_channel);
        EDMA_ResetChannel(DMA0, self->dma_io_update_set_channel);
        edma_transfer_config_t io_update_set_config;
        EDMA_PrepareTransfer(&io_update_set_config,
            &spi_dma_io_update_gpio_bit_mask, 4,
            (void *)&SPI_DMA_IO_UPDATE_GPIO_BASE->DR_SET, 4,
            4, 4, kEDMA_MemoryToPeripheral);
        memset(&spi_dma_io_update_set_tcd, 0, sizeof(edma_tcd_t));
        EDMA_TcdSetTransferConfig(&spi_dma_io_update_set_tcd, &io_update_set_config, &spi_dma_io_update_set_tcd);
        EDMA_InstallTCD(DMA0, self->dma_io_update_set_channel, &spi_dma_io_update_set_tcd);
        EDMA_StartTransfer(&self->dma_io_update_set_edmaHandle);

        EDMA_CreateHandle(&self->dma_io_update_clear_edmaHandle, DMA0, self->dma_io_update_clear_channel);
        EDMA_ResetChannel(DMA0, self->dma_io_update_clear_channel);
        edma_transfer_config_t io_update_clear_config;
        EDMA_PrepareTransfer(&io_update_clear_config,
            &spi_dma_io_update_gpio_bit_mask, 4,
            (void *)&SPI_DMA_IO_UPDATE_GPIO_BASE->DR_CLEAR, 4,
            4, 4, kEDMA_MemoryToPeripheral);
        memset(&spi_dma_io_update_clear_tcd, 0, sizeof(edma_tcd_t));
        EDMA_TcdSetTransferConfig(&spi_dma_io_update_clear_tcd, &io_update_clear_config, &spi_dma_io_update_clear_tcd);
        EDMA_InstallTCD(DMA0, self->dma_io_update_clear_channel, &spi_dma_io_update_clear_tcd);
        EDMA_StartTransfer(&self->dma_io_update_clear_edmaHandle);

        PIT_StartTimer(PIT, SPI_DMA_IO_UPDATE_RISE_PIT_CHANNEL);
        PIT_StartTimer(PIT, SPI_DMA_IO_UPDATE_FALL_PIT_CHANNEL);
        // Rewrite both LDVALs to the real period now that each channel has already
        // latched its short one-shot value into CVAL at start -- per fsl_pit.h, this
        // only takes effect on the SECOND and later reloads (see the module comment),
        // leaving both channels offset from SPI_DMA_PIT_CHANNEL by phase_ticks /
        // phase_ticks+pulse_width_ticks forever, with zero drift between them.
        PIT_SetTimerPeriod(PIT, SPI_DMA_IO_UPDATE_RISE_PIT_CHANNEL, pit_ticks);
        PIT_SetTimerPeriod(PIT, SPI_DMA_IO_UPDATE_FALL_PIT_CHANNEL, pit_ticks);
    } else {
        self->dma_io_update_set_channel = -1;
        self->dma_io_update_clear_channel = -1;
    }

    // --- LPSPI frame-size fixup: a single AD9910/9952/9954 register write is one
    // instruction byte + N payload bytes inside ONE continuous chip-select-low window
    // (the datasheet's own serial-port timing diagram), not N+1 separate one-byte
    // transactions. Left at whatever FRAMESZ a normal machine.SPI.write() call last
    // configured (LPSPI defaults effectively to one CS pulse per 8 bits), the DMA path
    // below would toggle PCS after every single byte instead of once per whole frame --
    // almost certainly misinterpreted by the DDS as N+1 separate short writes rather
    // than one real register write. Fixed by widening just the FRAMESZ field so hardware
    // holds PCS low across the whole frame_bytes*8-bit frame, auto-toggling it only
    // between frames.
    //
    // Deliberately a read-modify-write of TCR's existing value, not a from-scratch
    // reconstruction: TCR also carries CPOL/CPHA/PRESCALE/PCS-select/byte-swap, and
    // LPSPI_MasterInit() does not appear to fully populate TCR itself (those fields seem
    // to only get set for real when a transfer actually runs) -- so this call has a real
    // PRECONDITION: at least one ordinary spi.write()/write_readinto() must already have
    // succeeded on this object before dma_periodic_start() is called, so TCR already
    // holds this project's correct working CPOL/CPHA/byte-order configuration from that
    // call, and this code only widens FRAMESZ on top of it rather than guessing those
    // other fields from scratch (guessing PRESCALE's encoding or BYSW independently was
    // judged a worse risk than requiring this precondition). NOT bench-verified that this
    // read-modify-write approach actually produces correct multi-byte bit ordering on the
    // wire -- see the module comment's open-items list; capture with the ADALM2000 and
    // compare against a known-good blocking-mode write of the same register before
    // trusting this.
    uint32_t frame_bits = (uint32_t)self->dma_frame_bytes * 8;
    self->spi_inst->TCR = (self->spi_inst->TCR & ~LPSPI_TCR_FRAMESZ_MASK) | LPSPI_TCR_FRAMESZ(frame_bits - 1);

    // --- eDMA: PIT-triggered, ring buffer -> LPSPI TDR, self-linked TCD for
    // continuous circular operation (same construct machine_i2s.c uses). DMAMUX_Init()/
    // dma_init() already ran above (moved there so the I/O_UPDATE channels have an
    // initialized DMAMUX/DMA0 to configure too) -- not repeated here.
    self->dma_channel = allocate_dma_channel();
    if (self->dma_channel < 0) {
        mp_raise_msg(&mp_type_OSError, MP_ERROR_TEXT("no DMA channel available"));
    }
    DMAMUX_SetSource(DMAMUX, self->dma_channel, SPI_DMA_DMAMUX_SRC);
    DMAMUX_EnableChannel(DMAMUX, self->dma_channel);

    EDMA_CreateHandle(&self->dma_edmaHandle, DMA0, self->dma_channel);
    EDMA_SetCallback(&self->dma_edmaHandle, edma_spi_periodic_callback, self);
    EDMA_ResetChannel(DMA0, self->dma_channel);
    self->dma_edmaTcd = &spi_dma_tcd;

    // Per-beat transfer width MUST be a real eDMA SSIZE/DSIZE encoding (1/2/4/8/16/32
    // bytes) -- dma_frame_bytes (e.g. 9 for an AD9910 write) is NOT a valid width and an
    // earlier version of this patch wrongly passed it as one. Fixed: beats are always
    // 1 byte wide; dma_frame_bytes instead sets the MINOR LOOP byte count (how many
    // 1-byte beats fire back-to-back per single PIT-sourced DMA request) -- this is the
    // standard eDMA minor-loop/major-loop split, not a workaround.
    edma_transfer_config_t transferConfig;
    EDMA_PrepareTransfer(&transferConfig,
        self->dma_buffer_dcache_aligned, 1,
        (void *)&self->spi_inst->TDR, 1,
        (uint32_t)self->dma_frame_bytes,     // minor loop: one whole frame per QTMR tick
        (uint32_t)total_bytes,               // major loop: whole ring buffer
        kEDMA_MemoryToPeripheral);
    memset(self->dma_edmaTcd, 0, sizeof(edma_tcd_t));
    EDMA_TcdSetTransferConfig(self->dma_edmaTcd, &transferConfig, self->dma_edmaTcd);
    EDMA_TcdEnableInterrupts(self->dma_edmaTcd, kEDMA_MajorInterruptEnable | kEDMA_HalfInterruptEnable);
    EDMA_InstallTCD(DMA0, self->dma_channel, self->dma_edmaTcd);
    EDMA_StartTransfer(&self->dma_edmaHandle);

    PIT_StartTimer(PIT, SPI_DMA_PIT_CHANNEL);

    self->dma_periodic_active = true;
    return mp_const_none;
}
static MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN(machine_spi_dma_periodic_start_obj, 4, 6, machine_spi_dma_periodic_start);

// spi.dma_periodic_write(half, buf) -- copy buf (must be exactly SPI_DMA_FRAMES_PER_HALF
// * frame_bytes long) into the specified half (0=bottom, 1=top) of the internal ring
// buffer. Intended to be called from the refill_callback passed to
// dma_periodic_start(), using the `half` value that callback was invoked with.
static mp_obj_t machine_spi_dma_periodic_write(mp_obj_t self_in, mp_obj_t half_in, mp_obj_t buf_in) {
    machine_spi_obj_t *self = MP_OBJ_TO_PTR(self_in);
    mp_int_t half = mp_obj_get_int(half_in);
    if (!self->dma_periodic_active) {
        mp_raise_msg(&mp_type_OSError, MP_ERROR_TEXT("dma_periodic not active"));
    }
    mp_buffer_info_t buf;
    mp_get_buffer_raise(buf_in, &buf, MP_BUFFER_READ);
    size_t half_bytes = SPI_DMA_FRAMES_PER_HALF * self->dma_frame_bytes;
    if (buf.len != half_bytes) {
        mp_raise_ValueError(MP_ERROR_TEXT("buffer wrong length for one half"));
    }
    uint8_t *dest = self->dma_buffer_dcache_aligned + (half ? half_bytes : 0);
    memcpy(dest, buf.buf, half_bytes);
    // Confirmed necessary by bench test (2026-09-06) -- see dma_periodic_start()'s own
    // comment. Without this, DMA silently keeps reading whatever stale content was in
    // RAM before this call, ignoring every refill.
    DCACHE_CleanByRange((uint32_t)dest, (uint32_t)half_bytes);
    return mp_const_none;
}
static MP_DEFINE_CONST_FUN_OBJ_3(machine_spi_dma_periodic_write_obj, machine_spi_dma_periodic_write);

// Diagnostic-only (2026-09-06): see spi_dma_isr_count's own comment above.
static mp_obj_t machine_spi_dma_periodic_isr_count(mp_obj_t self_in) {
    (void)self_in;
    return mp_obj_new_int_from_uint(spi_dma_isr_count);
}
static MP_DEFINE_CONST_FUN_OBJ_1(machine_spi_dma_periodic_isr_count_obj, machine_spi_dma_periodic_isr_count);

static mp_obj_t machine_spi_dma_periodic_stop(mp_obj_t self_in) {
    machine_spi_obj_t *self = MP_OBJ_TO_PTR(self_in);
    if (!self->dma_periodic_active) {
        return mp_const_none;
    }
    EDMA_AbortTransfer(&self->dma_edmaHandle);
    free_dma_channel(self->dma_channel);
    PIT_StopTimer(PIT, SPI_DMA_PIT_CHANNEL);
    if (self->dma_io_update_set_channel >= 0) {
        EDMA_AbortTransfer(&self->dma_io_update_set_edmaHandle);
        free_dma_channel(self->dma_io_update_set_channel);
        self->dma_io_update_set_channel = -1;
    }
    if (self->dma_io_update_clear_channel >= 0) {
        EDMA_AbortTransfer(&self->dma_io_update_clear_edmaHandle);
        free_dma_channel(self->dma_io_update_clear_channel);
        self->dma_io_update_clear_channel = -1;
    }
    PIT_StopTimer(PIT, SPI_DMA_IO_UPDATE_RISE_PIT_CHANNEL);
    PIT_StopTimer(PIT, SPI_DMA_IO_UPDATE_FALL_PIT_CHANNEL);
    self->dma_periodic_active = false;
    self->dma_refill_callback = MP_OBJ_NULL;
    return mp_const_none;
}
static MP_DEFINE_CONST_FUN_OBJ_1(machine_spi_dma_periodic_stop_obj, machine_spi_dma_periodic_stop);

static void machine_spi_deinit_hw(mp_obj_base_t *self_in) {
    machine_spi_dma_periodic_stop(MP_OBJ_FROM_PTR(self_in));
}

// --- Port-specific locals dict: the generic mp_machine_spi_locals_dict (extmod/
// machine_spi.c) has no way to carry these mimxrt-only additions, so this file defines
// its own dict combining the generic entries with the three new methods above, and
// points machine_spi_type at THIS dict instead. The extern declarations below assume
// external linkage for the generic *_obj symbols -- consistent with how
// MP_DEFINE_CONST_FUN_OBJ_* is used elsewhere in this codebase, but NOT bench/build-
// verified for this exact case; a build failure here would mean extmod/machine_spi.c
// needs those symbols marked non-static (a one-line, upstream-friendly fix) rather than
// anything wrong with this file's own logic.
// mp_machine_spi_{read,readinto,write,write_readinto}_obj are already declared (with the
// correct types -- read/readinto as mp_obj_fun_builtin_var_t, write/write_readinto as
// mp_obj_fun_builtin_fixed_t) by extmod/modmachine.h, already transitively included via
// py/runtime.h above -- redeclaring them here with guessed types was a real build error
// (conflicting types for mp_machine_spi_write_obj), not just redundant. Only
// machine_spi_init_obj/machine_spi_deinit_obj need a fresh extern here: modmachine.h
// doesn't declare them (they were static in extmod/machine_spi.c until this patch).
extern const mp_obj_fun_builtin_var_t machine_spi_init_obj;    // MP_DEFINE_CONST_FUN_OBJ_KW
extern const mp_obj_fun_builtin_fixed_t machine_spi_deinit_obj; // MP_DEFINE_CONST_FUN_OBJ_1

static const mp_rom_map_elem_t machine_spi_mimxrt_locals_dict_table[] = {
    { MP_ROM_QSTR(MP_QSTR_init), MP_ROM_PTR(&machine_spi_init_obj) },
    { MP_ROM_QSTR(MP_QSTR_deinit), MP_ROM_PTR(&machine_spi_deinit_obj) },
    { MP_ROM_QSTR(MP_QSTR_read), MP_ROM_PTR(&mp_machine_spi_read_obj) },
    { MP_ROM_QSTR(MP_QSTR_readinto), MP_ROM_PTR(&mp_machine_spi_readinto_obj) },
    { MP_ROM_QSTR(MP_QSTR_write), MP_ROM_PTR(&mp_machine_spi_write_obj) },
    { MP_ROM_QSTR(MP_QSTR_write_readinto), MP_ROM_PTR(&mp_machine_spi_write_readinto_obj) },
    { MP_ROM_QSTR(MP_QSTR_MSB), MP_ROM_INT(MICROPY_PY_MACHINE_SPI_MSB) },
    { MP_ROM_QSTR(MP_QSTR_LSB), MP_ROM_INT(MICROPY_PY_MACHINE_SPI_LSB) },
    { MP_ROM_QSTR(MP_QSTR_dma_periodic_start), MP_ROM_PTR(&machine_spi_dma_periodic_start_obj) },
    { MP_ROM_QSTR(MP_QSTR_dma_periodic_write), MP_ROM_PTR(&machine_spi_dma_periodic_write_obj) },
    { MP_ROM_QSTR(MP_QSTR_dma_periodic_stop), MP_ROM_PTR(&machine_spi_dma_periodic_stop_obj) },
    { MP_ROM_QSTR(MP_QSTR_dma_periodic_isr_count), MP_ROM_PTR(&machine_spi_dma_periodic_isr_count_obj) },
};
MP_DEFINE_CONST_DICT(mp_machine_spi_mimxrt_locals_dict, machine_spi_mimxrt_locals_dict_table);

MP_DEFINE_CONST_OBJ_TYPE(
    machine_spi_type,
    MP_QSTR_SPI,
    MP_TYPE_FLAG_NONE,
    make_new, machine_spi_make_new,
    print, machine_spi_print,
    protocol, &machine_spi_p,
    locals_dict, &mp_machine_spi_mimxrt_locals_dict
    );
